name: Add label
on:
  pull_request:
    types:
      - opened
      - edited

  issues:
    types:
      - opened
      - reopened

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  triage:
    runs-on: ubuntu-latest

    env:
      PR_TITLE: ${{ github.event.pull_request.title }}
      ISSUE_TITLE: ${{ github.event.issue.title }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: âœ¨ feature label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith($PR_TITLE, 'feature:') || startsWith($ISSUE_TITLE, 'feature:') }}
        with:
          labels: âœ¨ feature

      - name: âœ… test label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(PR_TITLE, 'test:') || startsWith(ISSUE_TITLE, 'test:') }}
        with:
          labels: âœ… test

      - name: ğŸ bug
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(PR_TITLE, 'bug:') || startsWith(ISSUE_TITLE, 'bug:') }}
        with:
          labels: ğŸ bug

      - name: ğŸ§¹ chore
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(PR_TITLE, 'chore:') || startsWith(ISSUE_TITLE, 'chore:') }}
        with:
          labels: ğŸ§¹ chore

      - name: â™»ï¸ refactor
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(PR_TITLE, 'refactor:') || startsWith(ISSUE_TITLE, 'refactor:') }}
        with:
          labels: â™»ï¸ refactor

      - name: ğŸ“„ï¸ docs
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(PR_TITLE, 'docs:') || startsWith(ISSUE_TITLE, 'docs:') }}
        with:
          labels: ğŸ“„ï¸ docs

      - name: ğŸ”¨ï¸setting
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(PR_TITLE, 'setting:') || startsWith(ISSUE_TITLE, 'setting:') }}
        with:
          labels: ğŸ”¨ï¸setting
